# Generated by Django 3.1.6 on 2021-02-13 23:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name': 'Community', 'verbose_name_plural': 'Communities'},
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, upload_to='restaurants/', validators=[django.core.validators.validate_image_file_extension]),
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='vouchers/', validators=[django.core.validators.validate_image_file_extension])),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.restaurant')),
            ],
        ),
    ]
